### ISSUE TITLE
Null pointer exeption when via cost is high

### ISSUE THREAD

**Issue by djmerrill** [The-OpenROAD-Project/PcbRouter#2]
When via cost is set to >450 a null pointer exception is thrown.

**Comment by choltz95** [comment]
Occurs when any cost exceeds a threshold.

**Comment by k2973363** [comment]
Hello, the issue cannot be reproduced by giving 1000 to the layer_changing_cost. Please specify the environment, the used testcase and the full setup of the parameters.

**Comment by choltz95** [comment]
Can't reproduce the issue. Seems to have been resolved.
